remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme

title: Sharing ideas
description: In this website I share ideas, things I have learned, understood or are in the process of entering my mind. The content is about the things I'm interested into.

show_downloads: false